"""Change Company for api

Revision ID: 079b8b0f06d5
Revises: 0fc41c5fe563
Create Date: 2017-05-19 22:35:15.437807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '079b8b0f06d5'
down_revision = '0fc41c5fe563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('abstract', sa.Text(), nullable=False))
    op.alter_column('companies', 'crunchbase',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('companies', 'original_description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('companies', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('detail', mysql.TEXT(), nullable=False))
    op.alter_column('companies', 'original_description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('companies', 'crunchbase',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.drop_column('companies', 'abstract')
    # ### end Alembic commands ###
