"""Create table

Revision ID: 0fc41c5fe563
Revises: 
Create Date: 2017-05-19 22:19:42.665469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc41c5fe563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('crunchbase', sa.String(length=256), nullable=False),
        sa.Column('url', sa.String(length=256), nullable=False),
        sa.Column('detail', sa.Text(), nullable=False),
        sa.Column('original_description', sa.Text(), nullable=False),
        sa.Column('japanese_description', sa.Text(), nullable=True),
        sa.Column('founded_date', sa.Date(), nullable=True),
        sa.Column('categories', sa.String(length=256), nullable=True),
        sa.Column('news_page', sa.String(length=256), nullable=True),
        sa.Column('place', sa.String(length=32), nullable=True),
        sa.Column('funding', sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_crunchbase'), 'companies', ['crunchbase'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_url'), 'companies', ['url'], unique=True)
    op.create_table('news',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('media', sa.String(length=32), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('news_url', sa.String(length=256), nullable=False),
        sa.Column('company_name', sa.String(length=32), nullable=False),
        sa.Column('original_description', sa.Text(), nullable=True),
        sa.Column('japanese_description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_index(op.f('ix_companies_url'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_crunchbase'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
