"""Add url to master

Revision ID: 10407acae105
Revises: ec288e89aabb
Create Date: 2017-05-28 18:44:12.737109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10407acae105'
down_revision = 'ec288e89aabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('url', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_companies_url'), 'companies', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_url'), table_name='companies')
    op.drop_column('companies', 'url')
    # ### end Alembic commands ###
