"""Add logo image model

Revision ID: 1d28c7892d99
Revises: 49cb03d3cd01
Create Date: 2017-06-06 15:23:05.376932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d28c7892d99'
down_revision = '49cb03d3cd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logo_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('wordpress_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_url', sa.String(length=256), nullable=True),
    sa.Column('angellist_id', sa.Integer(), nullable=True),
    sa.Column('crunchbase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['angellist_id'], ['angellist_companies.id'], ),
    sa.ForeignKeyConstraint(['crunchbase_id'], ['crunchbase_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logo_images_url'), 'logo_images', ['url'], unique=False)
    op.create_index(op.f('ix_logo_images_wordpress_id'), 'logo_images', ['wordpress_id'], unique=False)
    op.drop_constraint('angellist_companies_ibfk_1', 'angellist_companies', type_='foreignkey')
    op.drop_column('angellist_companies', 'logo_image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angellist_companies', sa.Column('logo_image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('angellist_companies_ibfk_1', 'angellist_companies', 'images', ['logo_image_id'], ['id'])
    op.drop_index(op.f('ix_logo_images_wordpress_id'), table_name='logo_images')
    op.drop_index(op.f('ix_logo_images_url'), table_name='logo_images')
    op.drop_table('logo_images')
    # ### end Alembic commands ###
