"""Add video to al company

Revision ID: 42bd76bcc7f1
Revises: fd6dbf0f4177
Create Date: 2017-06-01 23:56:57.308445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bd76bcc7f1'
down_revision = 'fd6dbf0f4177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angellist_companies', sa.Column('video_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('angellist_companies', 'video_url')
    # ### end Alembic commands ###
