"""Modify logo image relationship

Revision ID: 49cb03d3cd01
Revises: 574519790105
Create Date: 2017-06-06 14:32:35.319517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cb03d3cd01'
down_revision = '574519790105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('angellist_companies', sa.Column('logo_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'angellist_companies', 'images', ['logo_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'angellist_companies', type_='foreignkey')
    op.drop_column('angellist_companies', 'logo_image_id')
    # ### end Alembic commands ###
