"""Add wp info to image and logo image relation_

Revision ID: 574519790105
Revises: 42bd76bcc7f1
Create Date: 2017-06-06 14:04:07.252416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574519790105'
down_revision = '42bd76bcc7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('wordpress_id', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('wordpress_url', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_images_wordpress_id'), 'images', ['wordpress_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_wordpress_id'), table_name='images')
    op.drop_column('images', 'wordpress_url')
    op.drop_column('images', 'wordpress_id')
    # ### end Alembic commands ###
