"""Add role to company

Revision ID: 6ca9f5713ea7
Revises: d3716c1cd86d
Create Date: 2017-05-20 00:42:46.094050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca9f5713ea7'
down_revision = 'd3716c1cd86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('role', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'role')
    # ### end Alembic commands ###
