"""Create Tables

Revision ID: a0e73775f57e
Revises: 
Create Date: 2017-05-19 23:50:41.869256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0e73775f57e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('news_url', sa.String(length=256), nullable=False),
    sa.Column('company_name', sa.String(length=32), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('japanese_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('abstract', sa.Text(), nullable=False))
    op.add_column('companies', sa.Column('japanese_abstract', sa.Text(), nullable=True))
    op.alter_column('companies', 'crunchbase',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('companies', 'original_description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_companies_crunchbase'), 'companies', ['crunchbase'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_url'), 'companies', ['url'], unique=False)
    op.drop_column('companies', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('detail', mysql.TEXT(), nullable=False))
    op.drop_index(op.f('ix_companies_url'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_crunchbase'), table_name='companies')
    op.alter_column('companies', 'original_description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('companies', 'crunchbase',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.drop_column('companies', 'japanese_abstract')
    op.drop_column('companies', 'abstract')
    op.drop_table('news')
    # ### end Alembic commands ###
