"""change string length

Revision ID: c47cee858b8a
Revises: 6ca9f5713ea7
Create Date: 2017-05-20 01:38:43.173490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47cee858b8a'
down_revision = '6ca9f5713ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
