"""Remove nullable false from companies prop

Revision ID: d3716c1cd86d
Revises: a0e73775f57e
Create Date: 2017-05-20 00:06:25.635746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3716c1cd86d'
down_revision = 'a0e73775f57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'abstract',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('companies', 'url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('companies', 'abstract',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
