"""Add company master and angellist. Rename table of crunchbase

Revision ID: ec288e89aabb
Revises: 0d3c342948ea
Create Date: 2017-05-28 17:40:35.539419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec288e89aabb'
down_revision = '0d3c342948ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('angellist_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angellist', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('japanese_abstract', sa.Text(), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('japanese_description', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('employers', sa.String(length=128), nullable=True),
    sa.Column('categories', sa.String(length=256), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angellist_companies_angellist'), 'angellist_companies', ['angellist'], unique=False)
    op.create_index(op.f('ix_angellist_companies_name'), 'angellist_companies', ['name'], unique=True)
    op.create_index(op.f('ix_angellist_companies_url'), 'angellist_companies', ['url'], unique=False)
    op.create_table('crunchbase_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('crunchbase', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('japanese_abstract', sa.Text(), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('japanese_description', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.Column('categories', sa.String(length=256), nullable=True),
    sa.Column('news_page', sa.String(length=256), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('funding', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crunchbase_companies_crunchbase'), 'crunchbase_companies', ['crunchbase'], unique=False)
    op.create_index(op.f('ix_crunchbase_companies_name'), 'crunchbase_companies', ['name'], unique=True)
    op.create_index(op.f('ix_crunchbase_companies_url'), 'crunchbase_companies', ['url'], unique=False)
    op.create_table('angellist_fundings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=256), nullable=True),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('raised', sa.String(length=128), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['angellist_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angellist_fundings_date'), 'angellist_fundings', ['date'], unique=False)
    op.add_column('companies', sa.Column('angellist_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('crunchbase_id', sa.Integer(), nullable=True))
    op.drop_index('ix_companies_crunchbase', table_name='companies')
    op.drop_index('ix_companies_url', table_name='companies')
    op.create_foreign_key(None, 'companies', 'crunchbase_companies', ['crunchbase_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'angellist_companies', ['angellist_id'], ['id'])
    op.drop_column('companies', 'role')
    op.drop_column('companies', 'news_page')
    op.drop_column('companies', 'crunchbase')
    op.drop_column('companies', 'japanese_description')
    op.drop_column('companies', 'url')
    op.drop_column('companies', 'place')
    op.drop_column('companies', 'original_description')
    op.drop_column('companies', 'japanese_abstract')
    op.drop_column('companies', 'funding')
    op.drop_column('companies', 'founded_date')
    op.drop_column('companies', 'categories')
    op.drop_column('companies', 'abstract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('abstract', mysql.TEXT(), nullable=True))
    op.add_column('companies', sa.Column('categories', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('founded_date', sa.DATE(), nullable=True))
    op.add_column('companies', sa.Column('funding', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('japanese_abstract', mysql.TEXT(), nullable=True))
    op.add_column('companies', sa.Column('original_description', mysql.TEXT(), nullable=True))
    op.add_column('companies', sa.Column('place', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('url', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('japanese_description', mysql.TEXT(), nullable=True))
    op.add_column('companies', sa.Column('crunchbase', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('news_page', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('companies', sa.Column('role', mysql.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_index('ix_companies_url', 'companies', ['url'], unique=False)
    op.create_index('ix_companies_crunchbase', 'companies', ['crunchbase'], unique=False)
    op.drop_column('companies', 'crunchbase_id')
    op.drop_column('companies', 'angellist_id')
    op.drop_index(op.f('ix_angellist_fundings_date'), table_name='angellist_fundings')
    op.drop_table('angellist_fundings')
    op.drop_index(op.f('ix_crunchbase_companies_url'), table_name='crunchbase_companies')
    op.drop_index(op.f('ix_crunchbase_companies_name'), table_name='crunchbase_companies')
    op.drop_index(op.f('ix_crunchbase_companies_crunchbase'), table_name='crunchbase_companies')
    op.drop_table('crunchbase_companies')
    op.drop_index(op.f('ix_angellist_companies_url'), table_name='angellist_companies')
    op.drop_index(op.f('ix_angellist_companies_name'), table_name='angellist_companies')
    op.drop_index(op.f('ix_angellist_companies_angellist'), table_name='angellist_companies')
    op.drop_table('angellist_companies')
    # ### end Alembic commands ###
